### ISSUE TITLE
Latest RKMC stretches widescreen videos to fullscreen bug

### ISSUE THREAD

**Issue by mo123** [JamesLinEngineer/RKMC#21]
Hi

Latest RKMC stretches widescreen videos to fullscreen.
Can it be fixed?

For videos being stretched.
Can try this test video, 4K 16:9 video.
http://4ksamples.com/elysium-4k-trailer/

RKMC before 21 Jan 2017 plays it in widescreen.
Latest RKMC stretches the video to fullscreen and then 'c' shortcut key also can't work any more to change zoom aspect of videos.

**Comment by JamesLinEngineer** [comment]
@mo123  Hi, I fix it with latest commit, please update and test it

**Comment by mo123** [comment]
@JamesLinEngineer HI, the problem is now much worse :(
On RK3288 Lollipop, widescreen videos that were stretched play correctly in widescreen now but videos that played in fullscreen are now also played in widescreen format.
On RK3229 Marshmallow a lot of 4K videos, 4096 resolution now show 8 vertical blocks of overlapping ghost images and at the bottom there are 10 green stripes so those videos are unwatchable now.
I can send you a picture if needed.
Any solution?

**Comment by JamesLinEngineer** [comment]
@mo123 
commit 266e359711fe8d399edaa7c1f60d1dcc8f2b05a2
Author: james.lin <james.lin@rock-chips.com>
Date:   Mon Feb 20 09:01:33 2017 +0800

    [RKCodec]: init surface rect as display resolution in surface mode
    
    Signed-off-by: james.lin <james.lin@rock-chips.com>
may help you

**Comment by mo123** [comment]
OK, it's fixed now.
Also had to update other files for RK3229 to fix the problem.
