### ISSUE TITLE
Build 1968ed6 3229 chip no audio passthrough

### ISSUE THREAD

**Issue by s13m11t7** [JamesLinEngineer/RKMC#5]
Hello, no audio passthrough ( dd, dts or multichannel lpcm ) on a 3229 system. No audio at all. Turn off passthrough and 2 channel lpcm works.

**Comment by JamesLinEngineer** [comment]
Hi please check if you sdk patch these https://github.com/JamesLinEngineer/RKMC/tree/Jarvis/RKMC-Patches/rk322x

**Comment by s13m11t7** [comment]
Hi James,

Sorry - I am a network engineer - not a software engineer.

I am happy to apply these patches - but I would require a process to follow.

If there is one available, I am happy to work through it.

If not, I will just wait until you commit these patches to your next build.

Thanks.

**Comment by s13m11t7** [comment]
Hi James,

Is passthrough available via hdmi, or only spdif? ( or both concurrently? )

Thanks

**Comment by mo123** [comment]
@s13m11t7 
You have to ask the manufacturer of your RK3229 to implement the SDK patches mentioned by James into their firmware. They then need to release a firmware update(software update) that you can flash to your RK3229 device. The patches need to be applied to the manufacturer's SDK, it can't be added to RKMC as RKMC is an Android app and the patches need to be applied to the Android Operating system by the manufacturer. Some companies like Firefly(RK3288) that make development boards release their SDK so users can apply the patches themselves and build their own firmware, but I haven’t seen a RK3229 company make a development board yet.

Pass-through is available via HDMI(5.1, 7.1) and SPDIF(5.1) but not both at the same time.

**Comment by s13m11t7** [comment]
I can confirm AC3 and DTS (5.1) Multichannel working after setting Sound Output to HDMI in Andorid settings.

Just have to wait for Multichannel PCM Android support now, otherwise HEVC working perfectly in this build.

**Comment by VincAlastor** [comment]
Sadly, i have to confirm until now multichannel PCM (hdmi passthrough)  isn't working. 

Is there a workaround for now?
